# Generated by Django 4.2.10 on 2024-03-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=200, verbose_name='URL')),
                ('blog_content', models.TextField(blank=True, null=True, verbose_name='содержимое')),
                ('blog_preview', models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='превью')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication_indicator', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('count_of_views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
    ]
