# Generated by Django 4.2.10 on 2024-03-31 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0003_alter_product_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.IntegerField(default=0, verbose_name='номер версии')),
                ('version_name', models.CharField(max_length=100, verbose_name='наименование версии')),
                ('version_indicator', models.BooleanField(default=True, verbose_name='признак версии')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product',
                                                   verbose_name='продукт')),
            ],
        ),
    ]
