# Generated by Django 4.2.10 on 2024-04-01 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0005_alter_version_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='product_name',
        ),
        migrations.AddField(
            model_name='version',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='catalog.product',
                                    verbose_name='продукт'),
            preserve_default=False,
        ),
    ]
